name: Build Kontacts

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gradle.properties
        run: |
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.nonTransitiveRClass=true" >> gradle.properties
          echo "enableJetifier=true" >> gradle.properties

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3
