name: Publish to Maven Central

on:
  release:
    types: [created] # triggers only when a new release is created

jobs:
  publish:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # need full history for Gradle release plugin

      - name: Setup gradle.properties
        run: |
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.nonTransitiveRClass=true" >> gradle.properties
          echo "enableJetifier=true" >> gradle.properties

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Publish to Maven Central
        run: ./gradlew publishAndReleaseToMavenCentral -Pversion=${{ github.event.release.tag_name }} --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
