name: Publish to Maven Central

on:
  push:
    branches:
      - develop

jobs:
  publish:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Bump version and create tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 || echo "1.0.0")
          echo "Latest tag: $LATEST_TAG"
          NEXT_TAG=$(echo $LATEST_TAG | awk -F. -v OFS=. '{$NF++; print}')
          echo "Next tag: $NEXT_TAG"
          git tag $NEXT_TAG
          git push origin $NEXT_TAG

      - name: Publish to Maven Central
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
